process.roles=broker

node.id=3

# WHERE to fetch metadata from (which controllers to connect to)
controller.quorum.voters=1@localhost:9093,2@localhost:9193

# This is where our Spring Boot apps(producer/consumer) will connect
listeners=BROKER://:9092

# passed this address to controller to store in their cluster metadata
advertised.listeners=BROKER://localhost:9092

# internally when follower broker try to fetch from leader, what listener they need to use.
inter.broker.listener.name=BROKER

# when broker try to communicate with controller what listener they need to use.
controller.listener.names=CONTROLLER

listener.security.protocol.map=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT

log.dirs=/tmp/broker1-logs

# Keep messages for 7 days (168 hours)
log.retention.hours=168

# Max size of a single log segment file (1GB)
log.segment.bytes=1073741824

# __consumer_offsets topic RF
offsets.topic.replication.factor=2
