process.roles=controller

node.id=2

listeners=CONTROLLER://:9193

controller.listener.names=CONTROLLER

controller.quorum.voters=1@localhost:9093,2@localhost:9193

# PLAINTEXT (no encryption). In production, we should use SSL.
listener.security.protocol.map=CONTROLLER:PLAINTEXT

log.dirs=/tmp/controller2-logs

# Default partitions when creating a topic without specifying
num.partitions=3

default.replication.factor=2
